### ISSUE TITLE
Cannot find backup or backup is not created

### ISSUE THREAD

**Issue by merlinuwe** [alberti42/obsidian-plugins-annotations#8] opened 2024-08-15 07:23 UTC
I'm testing the latest release on Windows 10.  I cannot find the backup I made, so I think it isn't generated.

![image](https://github.com/user-attachments/assets/f8c57f7a-a432-48de-a65d-82902f4ec566)

![image](https://github.com/user-attachments/assets/63947a70-923b-431d-ac84-95033c0749a0)

![image](https://github.com/user-attachments/assets/4cfd5526-1d0a-4098-b866-fa28228ca431)

**Comment by alberti42** [comment] 2024-08-15 09:20
Dear merlinuwe, thanks a lot for testing and reporting. The backups are made and stored in the same configuration file containing the settings. So they are happening under the hood.

You can export the current settings with the export button. The exported settings do not contain by design the previous setups. I did not include a button to export the individual setups. I am not sure how important it would be.

If you press on the restore button of any of your backups, you should see changes to be restored to the previous version.

I would appreciate if you can confirm it.

**Comment by alberti42** [comment] 2024-08-15 10:40
I have just released a new minor version of the app with (hopefully) a clearer explanation about what the buttons do. See screenshot below:

![Bildschirmfoto 2024-08-15 um 12 38 44](https://github.com/user-attachments/assets/9cc23f92-b8dc-4c2b-b59b-84a71b2777b9)

**Comment by merlinuwe** [comment] 2024-08-15 19:58
I confirm it. ;-)

The backup works, at least under Windows 10.

I could do this with all of my plugins:

![image](https://github.com/user-attachments/assets/84ed20a5-8e36-4a11-8d07-1f9f7d94a178)

The syntax I used is this:

![image](https://github.com/user-attachments/assets/384d2cab-fe67-4097-a540-66bb86b45d32)

The plugin seems to "eat" the line breaks I added after "markdown:" - no problem, only a remark.

---

The active link with the lock closed suggests that clicking on it will take you to the page with the description of the plugins. However, this is not the case, which is why I suggest hiding or greying out the link when the lock is closed.

Typo in the Instructions: ...will be dispalyed s Obsidian ... -> displayed

---

Dokumentation: If you dont give a path, the annotations are stored in the root vault, but one can remove them afterwards  to whatever place they like.

This confuses with

![image](https://github.com/user-attachments/assets/b3c0f5ca-c3e4-4c2f-a455-f75e2ed98fa9)

which function is not clear. (Why did the plugin store some annotations in the root vault when there is already a path defined?)

---

I use this in "Placeholder label:" because of my personal preference. 

[[Plugin - ${plugin_name}]]

You can add it to the documentation together with some _other_ examples. Meant for new users.

---

Use this text

Make changes only within the annotation blocks marked by `<!-- BEGIN ANNOTATION -->` and `<!-- END ANNOTATION -->`. Changes made anywhere else will be overwritten.

instead of 

Make changes only within the annotation blocks marked by  and . Changes made anywhere else will be overwritten.

to see this so 

![image](https://github.com/user-attachments/assets/dbf78eda-4cec-4f6e-b137-71cd0df5bf3e)


instead of 

![image](https://github.com/user-attachments/assets/252bcc7d-656b-4436-bb90-b60d965d3c57)

---

When I restart Obsidian, my links don't show as links, but as markdown. Unfortunately, they also don't work as links.  (Bug?)

![image](https://github.com/user-attachments/assets/0f671ffc-31fa-420f-aae4-6836489c6529)

**Comment by alberti42** [comment] 2024-08-18 02:42
Thanks a lot for the detailed and very useful feedback. I released a new version.

> The backup works, at least under Windows 10.

Great!

> The plugin seems to "eat" the line breaks I added after "markdown:" - no problem, only a remark.

This is by design. I don't see the usage for white empty lines. This is why they are trimmed.

> The active link with the lock closed suggests that clicking on it will take you to the page with the description of the plugins. However, this is not the case, which is why I suggest hiding or greying out the link when the lock is closed.

This was a bug. It took me some time, but it is not fixed.

> Typo in the Instructions: ...will be dispalyed s Obsidian ... -> displayed

FIxed.

**Comment by alberti42** [comment] 2024-08-18 02:45
> (Why did the plugin store some annotations in the root vault when there is already a path defined?)

This should not happen. It does not happen at least for me. I improved the explanation in the preference pane.

> Also in this context: I see a annotation file in my root folder:

Perhaps something created in some previous attempts?

> I use this in "Placeholder label:" because of my personal preference. You can add it to the documentation together with some other examples. Meant for new users.

Great idea. I did it.

**Comment by alberti42** [comment] 2024-08-18 02:52
> Make changes only within the annotation blocks marked by  and . Changes made anywhere else will be overwritten.

I improved this text. Now the block marks should be visible.

**Comment by alberti42** [comment] 2024-08-18 02:54
Since there were again many changes, I cannot exclude there is still a small bug here and there. I hope we will soon converge to a function that works as expected with no bugs. If you can test it, I would much appreciate it.

**Comment by merlinuwe** [comment] 2024-08-18 10:31
I made a backup of data.json, completely uninstalled the release and installed the lastest.

---

Importing my data.json works.

When I restore then from a data.json backup, where I manually deleted the first 2 entries, there is no change. I was expecting, that  the restored release overwrites the current settings.

---

I don't know why, but suddenly this appeared again in the root folder of my vault:

![image](https://github.com/user-attachments/assets/ed73637b-0a21-4d19-86e5-3dd2671445e7)

I guess, that I clicked it and there was no such file in `Obsidian\IT Grundlagen\MD Anleitungen\MD Obsidian Plugins`, so your plugin made one in the root vault.

Suggestion: Please add a path to the place where these annotation notes should be stored. I have long paths, that I dont like to see.

![image](https://github.com/user-attachments/assets/eb10531a-1244-4f02-b654-c707f9c99651)

Or can I change the annotation label? I use this 

[[IT Grundlagen/MD Anleitungen/MD Obsidian Plugins/Plugin - ${plugin_name}]]

**Comment by merlinuwe** [comment] 2024-08-18 13:57
What do I put into the fields to get a link to a annotation note (regardless if it already exists or not) like "[[Plugins - my plugin]]"?

[[IT Grundlagen/MD Anleitungen/MD Obsidian Plugins/Plugin - ${plugin_name}|Plugin - ${plugin_name}]]

[[Plugin - ${plugin_name}]]

I seem to overlook something.

**Comment by alberti42** [comment] 2024-08-18 21:12
Thank you for the detailed feedback and review of the plugin!

> Importing my data.json works.
>
> When I restore then from a data.json backup, where I manually deleted the first 2 entries, there is no change. I was  expecting, that the restored release overwrites the current settings.

I still fixed many bugs and changed the code. I cannot reproduce this behavior.  If you deleted two entries, then you will see the placeholder instead of the annotation. Could it be that you thought your original annotation was still there, but in reality it was the placeholder?

> Suggestion: Please add a path to the place where these annotation notes should be stored. I have long paths, that I dont like to see.

This is already fixed. I added a better explanation to the preference pane suggesting this example: `[[00 Meta/Installed plugins/${plugin_name} | ${plugin_name}]]`. Now, people can even click on the examples in the preference pane and select the text to be copied & pasted in the  corresponding setting field.

In your case, use the annotation `[[IT Grundlagen/MD Anleitungen/MD Obsidian Plugins/Plugin - ${plugin_name} | ${plugin_name}]]`

> What do I put into the fields to get a link to a annotation note (regardless if it already exists or not) like "[[Plugins - my plugin]]"?

I am not sure I understand the problem. Have you tried to configure both fields as in the image below:

![Bildschirmfoto 2024-08-18 um 19 44 16](https://github.com/user-attachments/assets/bcf01def-3b1a-4cc4-a089-3d535a6c53cf)

In this way, if you do not insert any annotation, you get the placeholder. When you add your own annotation, you still have the label preceding your annotation showing the automatic link.

> Both are working correct, but they are doubled.

Oh! I see. This was one of the many bugs I corrected today.

It seems a small plugin, but overall, the code became huge compared to the original starting point. I have rewritten a lot of code to improve it so that making changes has fewer chances to introduce new bugs.. but obviously, it is still not perfect.

**Comment by alberti42** [comment] 2024-08-18 21:13
I have not released the new version yet. I am still testing it.

**Comment by alberti42** [comment] 2024-08-19 16:30
Thanks a lot for your many comments. I just wanted to mention that the new release, as you know, 1.6.3 is now available. If you find the time in the coming days to test it, it is much appreciated.

**Comment by alberti42** [comment] 2024-10-12 08:59
I believe the issue has now been solved. I close the issue.

**Closed by alberti42** 2024-10-12 08:59 UTC
